export type Mission = 'control' | 'route' | 'sentinel' | 'debris' | 'investigations' | 'agents' | 'data' | 'impact' | 'status';
export interface Port {id:string;name:string;latitude:number;longitude:number;country?:string}
export interface Vessel {id:string;name:string;mmsi?:string;latitude:number;longitude:number;speed?:number;course?:number;timestamp?:string;source?:string;provenance?:string;events?:any[];track?:any[];geographic_context?:string;replay?:boolean;original_timestamp?:string}
export interface Provider {id:string;name:string;status:string;records:number|null;provenance:string;detail?:string;last_refresh?:string;dataset?:string}
export interface Trace {agent:string;agent_name?:string;timestamp:string;status:string;message:string;output?:any}
export interface Bootstrap {providers:Provider[];stats:Record<string,number>;ports:Port[];vessels:Vessel[];debris:any[];hotspots:any[];marine:any[];agents:any[];scenarios:{routes:{origin_id:string;destination_id:string;name:string}[];investigations:string[];historical_investigations?:string[]};recent_missions?:{id:string;type:string}[]}
export interface ReplayState {session_id?:string;status:'RUNNING'|'PAUSED'|'COMPLETED'|'STOPPED'|'IDLE';vessel_id?:string;vessel_name?:string;source?:string;provenance?:string;speed?:number;observations?:number;index?:number;progress_pct?:number;current_timestamp?:string;geographic_context?:string;detail?:string}
export function mergeTraces(existing:Trace[],incoming:Trace[]):Trace[]{const found=new Map<string,Trace>();for(const t of [...existing,...incoming])found.set(`${t.timestamp}|${t.agent}|${t.message}`,t);return [...found.values()].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).slice(-80)}
export const emptyBootstrap:Bootstrap={providers:[],stats:{},ports:[],vessels:[],debris:[],hotspots:[],marine:[],agents:[],scenarios:{routes:[],investigations:[]}};
export async function api<T=any>(path:string,body?:unknown):Promise<T>{const r=await fetch(`/api/${path}`,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){let reason='The service is temporarily unavailable.';try{const d=await r.json();reason=typeof d.detail==='string'?d.detail:reason;}catch{}throw new Error(reason)}return r.json()}
export const num=(v:unknown,d=0)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-IN',{maximumFractionDigits:d}):'—';
